package day4.exceptions;

public class ExceptionHierarchyDemo {
	
	public static void m3() {
		throw new RuntimeException();
	}
	public static void m2() {
		m3();
	}
	
	public static void m1() {
		m2();
	}
	
	public static void main(String[] args)  {
		
		
		try{
			m1();
		}
		catch(Exception re){
			System.out.println("Caught in main.. will do some handling");
			re.printStackTrace();
		}
		catch(RuntimeException re){
			System.out.println("Caught in main.. will do some handling");
			re.printStackTrace();
		}
		
		
		System.out.println("Program ends here--");
		
	}

}
